In [1]:
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
a=[1,2,3,4,'124',4.5,]
b=np.array(a,dtype=str)
print(b)

['1' '2' '3' '4' '124' '4.5']


In [9]:
a=[1,2,3,4,'124',4.5,]
b=np.array(a*3)
print(b)

['1' '2' '3' '4' '124' '4.5' '1' '2' '3' '4' '124' '4.5' '1' '2' '3' '4'
 '124' '4.5']


In [11]:
b=np.ones(4,d)
b

array([ 1.,  1.,  1.,  1.])

In [21]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
b=np.full((3,4),5,dtype=float)
b

array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

In [ ]:
np.arange()
np.linespace()

In [30]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange()
np.linespace

In [33]:
b=np.linspace(2,10)
b

array([  2.        ,   2.16326531,   2.32653061,   2.48979592,
         2.65306122,   2.81632653,   2.97959184,   3.14285714,
         3.30612245,   3.46938776,   3.63265306,   3.79591837,
         3.95918367,   4.12244898,   4.28571429,   4.44897959,
         4.6122449 ,   4.7755102 ,   4.93877551,   5.10204082,
         5.26530612,   5.42857143,   5.59183673,   5.75510204,
         5.91836735,   6.08163265,   6.24489796,   6.40816327,
         6.57142857,   6.73469388,   6.89795918,   7.06122449,
         7.2244898 ,   7.3877551 ,   7.55102041,   7.71428571,
         7.87755102,   8.04081633,   8.20408163,   8.36734694,
         8.53061224,   8.69387755,   8.85714286,   9.02040816,
         9.18367347,   9.34693878,   9.51020408,   9.67346939,
         9.83673469,  10.        ])

In [35]:
print(b[1]-b[0])
print(b[3]-b[2])

0.163265306122
0.163265306122


In [41]:
b=np.linspace(2,10,5,dtype = int,endpoint=False)
b

array([2, 3, 5, 6, 8])

In [42]:
b=np.identity(3)
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
b=np.eye(3,4)

In [44]:
b

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [51]:
b=np.random.rand(10)*10

In [52]:
b

array([ 4.98942364,  2.981725  ,  3.27573239,  5.00392447,  9.44829859,
        6.56421749,  5.89070981,  4.59761484,  4.3858499 ,  8.91291902])

In [53]:
import numpy as np

In [55]:
li=[2,3,4,45,5,6,6,7]
arr=np.array(li)
print(li)
print(arr)

[2, 3, 4, 45, 5, 6, 6, 7]
[ 2  3  4 45  5  6  6  7]


In [56]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(8,)
int32
(4,)


In [75]:
arr2d=[[1,2,3,4,],[2,3,4,5],[1,3,4,5]]
arr2=np.array(arr2d)

In [77]:
print(arr2d)
print(arr2)
print(arr2d[2][1])
print(arr2[2,1])



[[1, 2, 3, 4], [2, 3, 4, 5], [1, 3, 4, 5]]
[[1 2 3 4]
 [2 3 4 5]
 [1 3 4 5]]
3
3


In [67]:
print(arr2d.data)
print(arr2d.shape)
print(arr2d.dtype)
print(arr2d.strides)

AttributeError: 'list' object has no attribute 'data'

In [68]:
li=[1,2,3,34,54]
arr=np.array(li)
print(li)
print(arr)


[1, 2, 3, 34, 54]
[ 1  2  3 34 54]


In [71]:
print(li[2])
print(arr[2])
print(li[1:5])
print(arr[1:5])

3
3
[2, 3, 34, 54]
[ 2  3 34 54]


In [79]:
print(arr2d[1][:3])

[2, 3, 4]


In [80]:
print(arr2[1, :3])

[2 3 4]


In [83]:
print(arr2d[0:3][2])

[1, 3, 4, 5]


In [84]:
print(arr2d([0:3,2])

SyntaxError: invalid syntax (<ipython-input-84-5fbd85cbf7a8>, line 1)

In [15]:
import numpy as np
arrli=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr=np.array(arrli)
print(arr[1:3,1:3])


[[ 7  8]
 [12 13]]


In [18]:
import numpy as np
li=[1,2,3,4,5]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 6 16  8  5 10]
[ 9 18 12  8 11]


In [19]:
c=a+b

In [20]:
c

array([15, 34, 20, 13, 21])

In [21]:
a-b

array([-3, -2, -4, -3, -1])

In [22]:
a*b

array([ 54, 288,  96,  40, 110])

In [23]:
a/b

array([0.66666667, 0.88888889, 0.66666667, 0.625     , 0.90909091])

In [24]:
a//b

array([0, 0, 0, 0, 0], dtype=int32)

In [25]:
a**b

array([  10077696,          0,          0,     390625, 1215752192],
      dtype=int32)

In [26]:
a.sum()

45

In [27]:
a.mean()

9.0

In [28]:
a.min()

5

In [29]:
a.max()

16

In [30]:
a.argmax()

1

In [31]:
a
b

array([ 9, 18, 12,  8, 11])

In [32]:
print(a)
print(b)

[ 6 16  8  5 10]
[ 9 18 12  8 11]


In [33]:
a>b

array([False, False, False, False, False])

In [34]:
a<b

array([ True,  True,  True,  True,  True])

In [35]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [36]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [37]:
print(np.logical_not(a,b))

[0 0 0 0 0]


In [38]:
a[2]=0
print(a)


[ 6 16  0  5 10]


In [39]:
print(np.logical_not(a,b))

[0 0 1 0 0]


In [71]:
###boolean indexing in 1d array
import numpy as np
a=np.array(['t','u','r','s','y','z'])
b=np.random.randint(1,20,8)
print(a)            
print(b)

['t' 'u' 'r' 's' 'y' 'z']
[ 4 16 17 17 10  6  6  2]


In [72]:
print(b>10)

[False  True  True  True False False False False]


In [74]:
newarray=b[b>10]

In [75]:
newarray

array([16, 17, 17])

In [76]:
print(b)
c=b
c

[ 4 16 17 17 10  6  6  2]


array([ 4, 16, 17, 17, 10,  6,  6,  2])

In [77]:
c[:3]
c[c>15]=100

In [78]:
c

array([  4, 100, 100, 100,  10,   6,   6,   2])

In [79]:
print(b)

[  4 100 100 100  10   6   6   2]


In [80]:
print(b[b==100])

[100 100 100]


In [63]:
ind=np.where(b==100)

In [64]:
ind

(array([3, 5, 6, 7], dtype=int64),)

In [65]:
print(a)
print(b)

['t' 'u' 'r' 's' 'y' 'z']
[ 15  15   1 100   4 100 100 100]


In [81]:
ind=np.where(b==100)
print(ind)
print(a[ind])

(array([1, 2, 3], dtype=int64),)
['u' 'r' 's']


In [3]:
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[27  8 20  1 18  5]
 [ 2 16 16 22 12 11]
 [20 16 11 18  3 13]
 [21  1 12  8 10 24]
 [24 14 12 18 29 19]]


In [7]:
boolen_arr=a>20
print(boolen_arr)

[[ True False False False False False]
 [False False False  True False False]
 [False False False False False False]
 [ True False False False False  True]
 [ True False False False  True False]]


In [8]:
ans=a[boolen_arr]
print(ans)

[27 22 21 24 24 29]


In [11]:
b=a
print(a)

[[27  8 20  1 18  5]
 [ 2 16 16 22 12 11]
 [20 16 11 18  3 13]
 [21  1 12  8 10 24]
 [24 14 12 18 29 19]]


In [12]:
b[boolen_arr]=100
print(b)

[[100   8  20   1  18   5]
 [  2  16  16 100  12  11]
 [ 20  16  11  18   3  13]
 [100   1  12   8  10 100]
 [100  14  12  18 100  19]]


In [13]:
c=np.random.randint(1,10,(2,2));
print(c)

[[6 7]
 [5 4]]


In [14]:
print(b)

[[100   8  20   1  18   5]
 [  2  16  16 100  12  11]
 [ 20  16  11  18   3  13]
 [100   1  12   8  10 100]
 [100  14  12  18 100  19]]


In [17]:
bool_arr=b[:3]==100
print(bool_arr)


[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
